import type { CompanyConfig } from "@/types";

/**
 * Registry of all supported company tech blogs.
 *
 * Medium-based blogs use the medium.com/feed/<publication> format
 * to avoid SSL certificate issues with custom domains.
 */
export const COMPANY_CONFIGS: CompanyConfig[] = [
  // ═══════════════════════════════════════════════════════
  // ─── FAANG / Big Tech ─────────────────────────────────
  // ═══════════════════════════════════════════════════════
  {
    name: "Netflix",
    slug: "netflix",
    logo: "https://www.google.com/s2/favicons?domain=netflix.com&sz=128",
    website: "https://netflix.com",
    blogUrl: "https://netflixtechblog.com",
    feedUrl: "https://medium.com/feed/netflix-techblog",
    feedType: "rss",
    color: "#E50914",
  },
  {
    name: "Meta",
    slug: "meta",
    logo: "https://www.google.com/s2/favicons?domain=meta.com&sz=128",
    website: "https://meta.com",
    blogUrl: "https://engineering.fb.com",
    feedUrl: "https://engineering.fb.com/feed/",
    feedType: "rss",
    color: "#0081FB",
  },
  {
    name: "Google",
    slug: "google",
    logo: "https://www.google.com/s2/favicons?domain=google.com&sz=128",
    website: "https://google.com",
    blogUrl: "https://blog.google/technology",
    feedUrl: "https://blog.google/technology/rss/",
    feedType: "rss",
    color: "#4285F4",
  },
  {
    name: "AWS",
    slug: "aws",
    logo: "https://www.google.com/s2/favicons?domain=aws.amazon.com&sz=128",
    website: "https://aws.amazon.com",
    blogUrl: "https://aws.amazon.com/blogs/architecture",
    feedUrl: "https://aws.amazon.com/blogs/architecture/feed/",
    feedType: "rss",
    color: "#FF9900",
  },
  {
    name: "Microsoft",
    slug: "microsoft",
    logo: "https://www.google.com/s2/favicons?domain=microsoft.com&sz=128",
    website: "https://microsoft.com",
    blogUrl: "https://devblogs.microsoft.com",
    feedUrl: "https://devblogs.microsoft.com/engineering-at-microsoft/feed/",
    feedType: "rss",
    color: "#5E5E5E",
  },
  {
    name: "Apple",
    slug: "apple",
    logo: "https://www.google.com/s2/favicons?domain=apple.com&sz=128",
    website: "https://apple.com",
    blogUrl: "https://machinelearning.apple.com",
    feedUrl: "https://machinelearning.apple.com/rss.xml",
    feedType: "rss",
    color: "#000000",
  },

  // ═══════════════════════════════════════════════════════
  // ─── Developer Tools & Cloud ──────────────────────────
  // ═══════════════════════════════════════════════════════
  {
    name: "GitHub",
    slug: "github",
    logo: "https://www.google.com/s2/favicons?domain=github.com&sz=128",
    website: "https://github.com",
    blogUrl: "https://github.blog/engineering",
    feedUrl: "https://github.blog/engineering/feed/",
    feedType: "rss",
    color: "#181717",
  },
  {
    name: "GitLab",
    slug: "gitlab",
    logo: "https://www.google.com/s2/favicons?domain=gitlab.com&sz=128",
    website: "https://gitlab.com",
    blogUrl: "https://about.gitlab.com/blog/engineering",
    feedUrl: "https://about.gitlab.com/atom.xml",
    feedType: "rss",
    color: "#FC6D26",
  },
  {
    name: "Cloudflare",
    slug: "cloudflare",
    logo: "https://www.google.com/s2/favicons?domain=cloudflare.com&sz=128",
    website: "https://cloudflare.com",
    blogUrl: "https://blog.cloudflare.com",
    feedUrl: "https://blog.cloudflare.com/rss/",
    feedType: "rss",
    color: "#F38020",
  },
  {
    name: "HashiCorp",
    slug: "hashicorp",
    logo: "https://www.google.com/s2/favicons?domain=hashicorp.com&sz=128",
    website: "https://hashicorp.com",
    blogUrl: "https://www.hashicorp.com/blog",
    feedUrl: "https://www.hashicorp.com/blog/feed.xml",
    feedType: "rss",
    color: "#000000",
  },

  {
    name: "Vercel",
    slug: "vercel",
    logo: "https://www.google.com/s2/favicons?domain=vercel.com&sz=128",
    website: "https://vercel.com",
    blogUrl: "https://vercel.com/blog",
    feedUrl: "https://vercel.com/atom",
    feedType: "rss",
    color: "#000000",
  },

  {
    name: "Supabase",
    slug: "supabase",
    logo: "https://www.google.com/s2/favicons?domain=supabase.com&sz=128",
    website: "https://supabase.com",
    blogUrl: "https://supabase.com/blog",
    feedUrl: "https://supabase.com/rss.xml",
    feedType: "rss",
    color: "#3FCF8E",
  },
  {
    name: "PlanetScale",
    slug: "planetscale",
    logo: "https://www.google.com/s2/favicons?domain=planetscale.com&sz=128",
    website: "https://planetscale.com",
    blogUrl: "https://planetscale.com/blog",
    feedUrl: "https://planetscale.com/blog/feed.atom",
    feedType: "rss",
    color: "#000000",
  },
  {
    name: "Docker",
    slug: "docker",
    logo: "https://www.google.com/s2/favicons?domain=docker.com&sz=128",
    website: "https://docker.com",
    blogUrl: "https://www.docker.com/blog",
    feedUrl: "https://www.docker.com/blog/feed/",
    feedType: "rss",
    color: "#2496ED",
  },
  {
    name: "Grafana",
    slug: "grafana",
    logo: "https://www.google.com/s2/favicons?domain=grafana.com&sz=128",
    website: "https://grafana.com",
    blogUrl: "https://grafana.com/blog",
    feedUrl: "https://grafana.com/blog/index.xml",
    feedType: "rss",
    color: "#F46800",
  },
  {
    name: "Datadog",
    slug: "datadog",
    logo: "https://www.google.com/s2/favicons?domain=datadoghq.com&sz=128",
    website: "https://datadoghq.com",
    blogUrl: "https://www.datadoghq.com/blog/engineering",
    feedUrl: "https://www.datadoghq.com/blog/rss.xml",
    feedType: "rss",
    color: "#632CA6",
  },
  {
    name: "Elastic",
    slug: "elastic",
    logo: "https://www.google.com/s2/favicons?domain=elastic.co&sz=128",
    website: "https://elastic.co",
    blogUrl: "https://www.elastic.co/blog",
    feedUrl: "https://www.elastic.co/blog/feed/",
    feedType: "rss",
    color: "#005571",
  },
  {
    name: "MongoDB",
    slug: "mongodb",
    logo: "https://www.google.com/s2/favicons?domain=mongodb.com&sz=128",
    website: "https://mongodb.com",
    blogUrl: "https://www.mongodb.com/blog",
    feedUrl: "https://www.mongodb.com/blog/rss",
    feedType: "rss",
    color: "#47A248",
  },
  {
    name: "Redis",
    slug: "redis",
    logo: "https://www.google.com/s2/favicons?domain=redis.io&sz=128",
    website: "https://redis.io",
    blogUrl: "https://redis.io/blog",
    feedUrl: "https://redis.io/blog/feed/",
    feedType: "rss",
    color: "#FF4438",
  },
  {
    name: "Confluent",
    slug: "confluent",
    logo: "https://www.google.com/s2/favicons?domain=confluent.io&sz=128",
    website: "https://confluent.io",
    blogUrl: "https://www.confluent.io/blog",
    feedUrl: "https://www.confluent.io/feed/",
    feedType: "rss",
    color: "#173361",
  },

  // ═══════════════════════════════════════════════════════
  // ─── Fintech & Payments ───────────────────────────────
  // ═══════════════════════════════════════════════════════
  {
    name: "Stripe",
    slug: "stripe",
    logo: "https://www.google.com/s2/favicons?domain=stripe.com&sz=128",
    website: "https://stripe.com",
    blogUrl: "https://stripe.com/blog",
    feedUrl: "https://stripe.com/blog/feed.rss",
    feedType: "rss",
    color: "#635BFF",
  },
  {
    name: "Square",
    slug: "square",
    logo: "https://www.google.com/s2/favicons?domain=squareup.com&sz=128",
    website: "https://squareup.com",
    blogUrl: "https://developer.squareup.com/blog",
    feedUrl: "https://developer.squareup.com/blog/rss.xml",
    feedType: "rss",
    color: "#006AFF",
  },
  {
    name: "PayPal",
    slug: "paypal",
    logo: "https://www.google.com/s2/favicons?domain=paypal.com&sz=128",
    website: "https://paypal.com",
    blogUrl: "https://medium.com/paypal-tech",
    feedUrl: "https://medium.com/feed/paypal-tech",
    feedType: "rss",
    color: "#003087",
  },
  {
    name: "Robinhood",
    slug: "robinhood",
    logo: "https://www.google.com/s2/favicons?domain=robinhood.com&sz=128",
    website: "https://robinhood.com",
    blogUrl: "https://newsroom.aboutrobinhood.com/category/engineering",
    feedUrl: "https://medium.com/feed/robinhood-engineering",
    feedType: "rss",
    color: "#00C805",
  },
  {
    name: "Coinbase",
    slug: "coinbase",
    logo: "https://www.google.com/s2/favicons?domain=coinbase.com&sz=128",
    website: "https://coinbase.com",
    blogUrl: "https://www.coinbase.com/blog",
    feedUrl: "https://medium.com/feed/the-coinbase-blog",
    feedType: "rss",
    color: "#0052FF",
  },

  // ═══════════════════════════════════════════════════════
  // ─── Social & Communication ───────────────────────────
  // ═══════════════════════════════════════════════════════
  {
    name: "Spotify",
    slug: "spotify",
    logo: "https://www.google.com/s2/favicons?domain=spotify.com&sz=128",
    website: "https://spotify.com",
    blogUrl: "https://engineering.atspotify.com",
    feedUrl: "https://engineering.atspotify.com/feed/",
    feedType: "rss",
    color: "#1DB954",
  },
  {
    name: "Airbnb",
    slug: "airbnb",
    logo: "https://www.google.com/s2/favicons?domain=airbnb.com&sz=128",
    website: "https://airbnb.com",
    blogUrl: "https://medium.com/airbnb-engineering",
    feedUrl: "https://medium.com/feed/airbnb-engineering",
    feedType: "rss",
    color: "#FF5A5F",
  },
  {
    name: "Dropbox",
    slug: "dropbox",
    logo: "https://www.google.com/s2/favicons?domain=dropbox.com&sz=128",
    website: "https://dropbox.com",
    blogUrl: "https://dropbox.tech",
    feedUrl: "https://dropbox.tech/feed",
    feedType: "rss",
    color: "#0061FF",
  },
  {
    name: "LinkedIn",
    slug: "linkedin",
    logo: "https://www.google.com/s2/favicons?domain=linkedin.com&sz=128",
    website: "https://linkedin.com",
    blogUrl: "https://engineering.linkedin.com",
    feedUrl: "https://engineering.linkedin.com/blog.rss.html",
    feedType: "rss",
    color: "#0A66C2",
  },
  {
    name: "Twitter",
    slug: "twitter",
    logo: "https://www.google.com/s2/favicons?domain=x.com&sz=128",
    website: "https://x.com",
    blogUrl: "https://blog.twitter.com/engineering",
    feedUrl: "https://blog.x.com/engineering/en_us/blog.rss",
    feedType: "rss",
    color: "#1DA1F2",
  },
  {
    name: "Pinterest",
    slug: "pinterest",
    logo: "https://www.google.com/s2/favicons?domain=pinterest.com&sz=128",
    website: "https://pinterest.com",
    blogUrl: "https://medium.com/pinterest-engineering",
    feedUrl: "https://medium.com/feed/pinterest-engineering",
    feedType: "rss",
    color: "#E60023",
  },
  {
    name: "Slack",
    slug: "slack",
    logo: "https://www.google.com/s2/favicons?domain=slack.com&sz=128",
    website: "https://slack.com",
    blogUrl: "https://slack.engineering",
    feedUrl: "https://slack.engineering/feed/",
    feedType: "rss",
    color: "#4A154B",
  },
  {
    name: "Discord",
    slug: "discord",
    logo: "https://www.google.com/s2/favicons?domain=discord.com&sz=128",
    website: "https://discord.com",
    blogUrl: "https://discord.com/blog",
    feedUrl: "https://discord.com/blog/rss.xml",
    feedType: "rss",
    color: "#5865F2",
  },
  {
    name: "Snap",
    slug: "snap",
    logo: "https://www.google.com/s2/favicons?domain=snap.com&sz=128",
    website: "https://snap.com",
    blogUrl: "https://eng.snap.com",
    feedUrl: "https://eng.snap.com/feed",
    feedType: "rss",
    color: "#FFFC00",
  },
  {
    name: "Reddit",
    slug: "reddit",
    logo: "https://www.google.com/s2/favicons?domain=reddit.com&sz=128",
    website: "https://reddit.com",
    blogUrl: "https://www.reddit.com/r/RedditEng",
    feedUrl: "https://www.reddit.com/r/RedditEng/.rss",
    feedType: "rss",
    color: "#FF4500",
  },
  {
    name: "Tumblr",
    slug: "tumblr",
    logo: "https://www.google.com/s2/favicons?domain=tumblr.com&sz=128",
    website: "https://tumblr.com",
    blogUrl: "https://engineering.tumblr.com",
    feedUrl: "https://engineering.tumblr.com/rss",
    feedType: "rss",
    color: "#36465D",
  },

  // ═══════════════════════════════════════════════════════
  // ─── E-Commerce & Marketplace ─────────────────────────
  // ═══════════════════════════════════════════════════════
  {
    name: "Shopify",
    slug: "shopify",
    logo: "https://www.google.com/s2/favicons?domain=shopify.com&sz=128",
    website: "https://shopify.com",
    blogUrl: "https://shopify.engineering",
    feedUrl: "https://shopify.engineering/blog.atom",
    feedType: "rss",
    color: "#7AB55C",
  },
  {
    name: "eBay",
    slug: "ebay",
    logo: "https://www.google.com/s2/favicons?domain=ebay.com&sz=128",
    website: "https://ebay.com",
    blogUrl: "https://tech.ebayinc.com",
    feedUrl: "https://tech.ebayinc.com/rss/",
    feedType: "rss",
    color: "#E53238",
  },
  {
    name: "Etsy",
    slug: "etsy",
    logo: "https://www.google.com/s2/favicons?domain=etsy.com&sz=128",
    website: "https://etsy.com",
    blogUrl: "https://www.etsy.com/codeascraft",
    feedUrl: "https://www.etsy.com/codeascraft/rss",
    feedType: "rss",
    color: "#F16521",
  },
  {
    name: "Instacart",
    slug: "instacart",
    logo: "https://www.google.com/s2/favicons?domain=instacart.com&sz=128",
    website: "https://instacart.com",
    blogUrl: "https://tech.instacart.com",
    feedUrl: "https://tech.instacart.com/feed",
    feedType: "rss",
    color: "#43B02A",
  },
  {
    name: "Walmart",
    slug: "walmart",
    logo: "https://www.google.com/s2/favicons?domain=walmart.com&sz=128",
    website: "https://walmart.com",
    blogUrl: "https://medium.com/walmartglobaltech",
    feedUrl: "https://medium.com/feed/walmartglobaltech",
    feedType: "rss",
    color: "#0071CE",
  },

  // ═══════════════════════════════════════════════════════
  // ─── Ride-hailing & Delivery ──────────────────────────
  // ═══════════════════════════════════════════════════════
  {
    name: "Uber",
    slug: "uber",
    logo: "https://www.google.com/s2/favicons?domain=uber.com&sz=128",
    website: "https://uber.com",
    blogUrl: "https://www.uber.com/blog/engineering",
    feedUrl: "https://www.uber.com/blog/engineering/rss/",
    feedType: "rss",
    color: "#000000",
  },
  {
    name: "Lyft",
    slug: "lyft",
    logo: "https://www.google.com/s2/favicons?domain=lyft.com&sz=128",
    website: "https://lyft.com",
    blogUrl: "https://eng.lyft.com",
    feedUrl: "https://eng.lyft.com/feed",
    feedType: "rss",
    color: "#FF00BF",
  },
  {
    name: "Grab",
    slug: "grab",
    logo: "https://www.google.com/s2/favicons?domain=grab.com&sz=128",
    website: "https://grab.com",
    blogUrl: "https://engineering.grab.com",
    feedUrl: "https://engineering.grab.com/feed.xml",
    feedType: "rss",
    color: "#00B14F",
  },

  // ═══════════════════════════════════════════════════════
  // ─── Streaming & Entertainment ────────────────────────
  // ═══════════════════════════════════════════════════════
  {
    name: "Yelp",
    slug: "yelp",
    logo: "https://www.google.com/s2/favicons?domain=yelp.com&sz=128",
    website: "https://yelp.com",
    blogUrl: "https://engineeringblog.yelp.com",
    feedUrl: "https://engineeringblog.yelp.com/feed.xml",
    feedType: "rss",
    color: "#D32323",
  },

  // ═══════════════════════════════════════════════════════
  // ─── SaaS & Enterprise ────────────────────────────────
  // ═══════════════════════════════════════════════════════
  {
    name: "Atlassian",
    slug: "atlassian",
    logo: "https://www.google.com/s2/favicons?domain=atlassian.com&sz=128",
    website: "https://atlassian.com",
    blogUrl: "https://www.atlassian.com/engineering",
    feedUrl: "https://www.atlassian.com/engineering/feed",
    feedType: "rss",
    color: "#0052CC",
  },
  {
    name: "Salesforce",
    slug: "salesforce",
    logo: "https://www.google.com/s2/favicons?domain=salesforce.com&sz=128",
    website: "https://salesforce.com",
    blogUrl: "https://engineering.salesforce.com",
    feedUrl: "https://engineering.salesforce.com/feed/",
    feedType: "rss",
    color: "#00A1E0",
  },
  {
    name: "Twilio",
    slug: "twilio",
    logo: "https://www.google.com/s2/favicons?domain=twilio.com&sz=128",
    website: "https://twilio.com",
    blogUrl: "https://www.twilio.com/blog",
    feedUrl: "https://www.twilio.com/blog/feed",
    feedType: "rss",
    color: "#F22F46",
  },
  {
    name: "HubSpot",
    slug: "hubspot",
    logo: "https://www.google.com/s2/favicons?domain=hubspot.com&sz=128",
    website: "https://hubspot.com",
    blogUrl: "https://product.hubspot.com/blog",
    feedUrl: "https://product.hubspot.com/blog/rss.xml",
    feedType: "rss",
    color: "#FF7A59",
  },
  {
    name: "Canva",
    slug: "canva",
    logo: "https://www.google.com/s2/favicons?domain=canva.com&sz=128",
    website: "https://canva.com",
    blogUrl: "https://canvatechblog.com",
    feedUrl: "https://www.canva.dev/blog/engineering/feed.xml",
    feedType: "rss",
    color: "#00C4CC",
  },

  {
    name: "Figma",
    slug: "figma",
    logo: "https://www.google.com/s2/favicons?domain=figma.com&sz=128",
    website: "https://figma.com",
    blogUrl: "https://www.figma.com/blog/engineering",
    feedUrl: "https://www.figma.com/blog/feed/",
    feedType: "rss",
    color: "#F24E1E",
  },
  {
    name: "Miro",
    slug: "miro",
    logo: "https://www.google.com/s2/favicons?domain=miro.com&sz=128",
    website: "https://miro.com",
    blogUrl: "https://medium.com/miro-engineering",
    feedUrl: "https://medium.com/feed/miro-engineering",
    feedType: "rss",
    color: "#FFD02F",
  },

  {
    name: "Zoom",
    slug: "zoom",
    logo: "https://www.google.com/s2/favicons?domain=zoom.us&sz=128",
    website: "https://zoom.us",
    blogUrl: "https://medium.com/zoom-developer-blog",
    feedUrl: "https://medium.com/feed/zoom-developer-blog",
    feedType: "rss",
    color: "#0B5CFF",
  },

  // ═══════════════════════════════════════════════════════
  // ─── AI & ML ──────────────────────────────────────────
  // ═══════════════════════════════════════════════════════
  {
    name: "OpenAI",
    slug: "openai",
    logo: "https://www.google.com/s2/favicons?domain=openai.com&sz=128",
    website: "https://openai.com",
    blogUrl: "https://openai.com/research",
    feedUrl: "https://openai.com/blog/rss.xml",
    feedType: "rss",
    color: "#412991",
  },
  {
    name: "DeepMind",
    slug: "deepmind",
    logo: "https://www.google.com/s2/favicons?domain=deepmind.google&sz=128",
    website: "https://deepmind.google",
    blogUrl: "https://deepmind.google/discover/blog",
    feedUrl: "https://deepmind.google/blog/rss.xml",
    feedType: "rss",
    color: "#4285F4",
  },
  {
    name: "Hugging Face",
    slug: "huggingface",
    logo: "https://www.google.com/s2/favicons?domain=huggingface.co&sz=128",
    website: "https://huggingface.co",
    blogUrl: "https://huggingface.co/blog",
    feedUrl: "https://huggingface.co/blog/feed.xml",
    feedType: "rss",
    color: "#FFD21E",
  },

  // ═══════════════════════════════════════════════════════
  // ─── Travel & Hospitality ─────────────────────────────
  // ═══════════════════════════════════════════════════════
  {
    name: "Booking.com",
    slug: "bookingcom",
    logo: "https://www.google.com/s2/favicons?domain=booking.com&sz=128",
    website: "https://booking.com",
    blogUrl: "https://blog.booking.com",
    feedUrl: "https://medium.com/feed/booking-com-development",
    feedType: "rss",
    color: "#003580",
  },
  {
    name: "Expedia",
    slug: "expedia",
    logo: "https://www.google.com/s2/favicons?domain=expedia.com&sz=128",
    website: "https://expedia.com",
    blogUrl: "https://medium.com/expedia-group-tech",
    feedUrl: "https://medium.com/feed/expedia-group-tech",
    feedType: "rss",
    color: "#003580",
  },
  {
    name: "Agoda",
    slug: "agoda",
    logo: "https://www.google.com/s2/favicons?domain=agoda.com&sz=128",
    website: "https://agoda.com",
    blogUrl: "https://medium.com/agoda-engineering",
    feedUrl: "https://medium.com/feed/agoda-engineering",
    feedType: "rss",
    color: "#5392F9",
  },

  // ═══════════════════════════════════════════════════════
  // ─── Gaming ───────────────────────────────────────────
  // ═══════════════════════════════════════════════════════
  {
    name: "Riot Games",
    slug: "riotgames",
    logo: "https://www.google.com/s2/favicons?domain=riotgames.com&sz=128",
    website: "https://riotgames.com",
    blogUrl: "https://technology.riotgames.com",
    feedUrl: "https://technology.riotgames.com/rss.xml",
    feedType: "rss",
    color: "#D32936",
  },
  {
    name: "Unity",
    slug: "unity",
    logo: "https://www.google.com/s2/favicons?domain=unity.com&sz=128",
    website: "https://unity.com",
    blogUrl: "https://blog.unity.com/engine-platform",
    feedUrl: "https://blog.unity.com/feed",
    feedType: "rss",
    color: "#000000",
  },

  // ═══════════════════════════════════════════════════════
  // ─── Telecom & Hardware ───────────────────────────────
  // ═══════════════════════════════════════════════════════
  {
    name: "Samsung",
    slug: "samsung",
    logo: "https://www.google.com/s2/favicons?domain=samsung.com&sz=128",
    website: "https://samsung.com",
    blogUrl: "https://developer.samsung.com/blog",
    feedUrl: "https://developer.samsung.com/blog/feed",
    feedType: "rss",
    color: "#1428A0",
  },

  // ═══════════════════════════════════════════════════════
  // ─── European Tech ────────────────────────────────────
  // ═══════════════════════════════════════════════════════
  {
    name: "Klarna",
    slug: "klarna",
    logo: "https://www.google.com/s2/favicons?domain=klarna.com&sz=128",
    website: "https://klarna.com",
    blogUrl: "https://engineering.klarna.com",
    feedUrl: "https://engineering.klarna.com/feed",
    feedType: "rss",
    color: "#FFB3C7",
  },
  {
    name: "Trivago",
    slug: "trivago",
    logo: "https://www.google.com/s2/favicons?domain=trivago.com&sz=128",
    website: "https://trivago.com",
    blogUrl: "https://tech.trivago.com",
    feedUrl: "https://tech.trivago.com/index.xml",
    feedType: "rss",
    color: "#007FAD",
  },
  {
    name: "Wise",
    slug: "wise",
    logo: "https://www.google.com/s2/favicons?domain=wise.com&sz=128",
    website: "https://wise.com",
    blogUrl: "https://medium.com/wise-engineering",
    feedUrl: "https://medium.com/feed/wise-engineering",
    feedType: "rss",
    color: "#9FE870",
  },
  {
    name: "Zalando",
    slug: "zalando",
    logo: "https://www.google.com/s2/favicons?domain=zalando.com&sz=128",
    website: "https://zalando.com",
    blogUrl: "https://engineering.zalando.com",
    feedUrl: "https://engineering.zalando.com/atom.xml",
    feedType: "rss",
    color: "#FF6900",
  },
  {
    name: "Monzo",
    slug: "monzo",
    logo: "https://www.google.com/s2/favicons?domain=monzo.com&sz=128",
    website: "https://monzo.com",
    blogUrl: "https://monzo.com/blog/technology",
    feedUrl: "https://monzo.com/blog/technology.rss",
    feedType: "rss",
    color: "#14233C",
  },
  {
    name: "N26",
    slug: "n26",
    logo: "https://www.google.com/s2/favicons?domain=n26.com&sz=128",
    website: "https://n26.com",
    blogUrl: "https://medium.com/insiden26",
    feedUrl: "https://medium.com/feed/insiden26",
    feedType: "rss",
    color: "#36A18B",
  },
  {
    name: "Revolut",
    slug: "revolut",
    logo: "https://www.google.com/s2/favicons?domain=revolut.com&sz=128",
    website: "https://revolut.com",
    blogUrl: "https://medium.com/revolut",
    feedUrl: "https://medium.com/feed/revolut",
    feedType: "rss",
    color: "#0075EB",
  },

  // ═══════════════════════════════════════════════════════
  // ─── Southeast Asian Tech ─────────────────────────────
  // ═══════════════════════════════════════════════════════
  {
    name: "Gojek",
    slug: "gojek",
    logo: "https://www.google.com/s2/favicons?domain=gojek.com&sz=128",
    website: "https://gojek.com",
    blogUrl: "https://www.gojek.io/blog",
    feedUrl: "https://medium.com/feed/gojekengineering",
    feedType: "rss",
    color: "#00AA13",
  },
  {
    name: "Carousell",
    slug: "carousell",
    logo: "https://www.google.com/s2/favicons?domain=carousell.com&sz=128",
    website: "https://carousell.com",
    blogUrl: "https://medium.com/carousell-insider",
    feedUrl: "https://medium.com/feed/carousell-insider",
    feedType: "rss",
    color: "#FF3C23",
  },

  // ═══════════════════════════════════════════════════════
  // ─── Chinese Tech Giants ──────────────────────────────
  // ═══════════════════════════════════════════════════════
  {
    name: "Alibaba Cloud",
    slug: "alibabacloud",
    logo: "https://www.google.com/s2/favicons?domain=alibabacloud.com&sz=128",
    website: "https://alibabacloud.com",
    blogUrl: "https://www.alibabacloud.com/blog",
    feedUrl: "https://medium.com/feed/alibaba-cloud",
    feedType: "rss",
    color: "#FF6A00",
  },
  {
    name: "ByteDance",
    slug: "bytedance",
    logo: "https://www.google.com/s2/favicons?domain=bytedance.com&sz=128",
    website: "https://bytedance.com",
    blogUrl: "https://medium.com/bytedance-engineering",
    feedUrl: "https://medium.com/feed/bytedance-engineering",
    feedType: "rss",
    color: "#3C8CFF",
  },

  // ═══════════════════════════════════════════════════════
  // ─── Indian Companies ─────────────────────────────────
  // ═══════════════════════════════════════════════════════
  {
    name: "CRED",
    slug: "cred",
    logo: "https://www.google.com/s2/favicons?domain=cred.club&sz=128",
    website: "https://cred.club",
    blogUrl: "https://engineering.cred.club",
    feedUrl: "https://medium.com/feed/cred-engineering",
    feedType: "rss",
    color: "#1A1A2E",
  },
  {
    name: "Razorpay",
    slug: "razorpay",
    logo: "https://www.google.com/s2/favicons?domain=razorpay.com&sz=128",
    website: "https://razorpay.com",
    blogUrl: "https://engineering.razorpay.com",
    feedUrl: "https://engineering.razorpay.com/feed",
    feedType: "rss",
    color: "#0C2451",
  },
  {
    name: "Zerodha",
    slug: "zerodha",
    logo: "https://www.google.com/s2/favicons?domain=zerodha.com&sz=128",
    website: "https://zerodha.com",
    blogUrl: "https://zerodha.tech",
    feedUrl: "https://zerodha.tech/blog/index.xml",
    feedType: "rss",
    color: "#387ED1",
  },
  {
    name: "Flipkart",
    slug: "flipkart",
    logo: "https://www.google.com/s2/favicons?domain=flipkart.com&sz=128",
    website: "https://flipkart.com",
    blogUrl: "https://blog.flipkart.tech",
    feedUrl: "https://blog.flipkart.tech/feed",
    feedType: "rss",
    color: "#F7D03F",
  },
  {
    name: "Swiggy",
    slug: "swiggy",
    logo: "https://www.google.com/s2/favicons?domain=swiggy.com&sz=128",
    website: "https://swiggy.com",
    blogUrl: "https://bytes.swiggy.com",
    feedUrl: "https://medium.com/feed/swiggy-bytes",
    feedType: "rss",
    color: "#FC8019",
  },
  {
    name: "Groww",
    slug: "groww",
    logo: "https://www.google.com/s2/favicons?domain=groww.in&sz=128",
    website: "https://groww.in",
    blogUrl: "https://tech.groww.in",
    feedUrl: "https://tech.groww.in/feed",
    feedType: "rss",
    color: "#5367FF",
  },
  {
    name: "Zomato",
    slug: "zomato",
    logo: "https://www.google.com/s2/favicons?domain=zomato.com&sz=128",
    website: "https://zomato.com",
    blogUrl: "https://www.zomato.com/blog/category/technology",
    feedUrl: "https://medium.com/feed/zomato-technology",
    feedType: "rss",
    color: "#E23744",
  },
  {
    name: "PhonePe",
    slug: "phonepe",
    logo: "https://www.google.com/s2/favicons?domain=phonepe.com&sz=128",
    website: "https://phonepe.com",
    blogUrl: "https://tech.phonepe.com",
    feedUrl: "https://medium.com/feed/phonepe-engineering",
    feedType: "rss",
    color: "#5F259F",
  },
  {
    name: "Meesho",
    slug: "meesho",
    logo: "https://www.google.com/s2/favicons?domain=meesho.io&sz=128",
    website: "https://meesho.com",
    blogUrl: "https://www.meesho.io/blog",
    feedUrl: "https://medium.com/feed/meesho-tech",
    feedType: "rss",
    color: "#E91E63",
  },
  {
    name: "ShareChat",
    slug: "sharechat",
    logo: "https://www.google.com/s2/favicons?domain=sharechat.com&sz=128",
    website: "https://sharechat.com",
    blogUrl: "https://medium.com/sharechat-techblog",
    feedUrl: "https://medium.com/feed/sharechat-techblog",
    feedType: "rss",
    color: "#FF3F6C",
  },
  {
    name: "Dream11",
    slug: "dream11",
    logo: "https://www.google.com/s2/favicons?domain=dream11.com&sz=128",
    website: "https://dream11.com",
    blogUrl: "https://medium.com/dream11-tech-blog",
    feedUrl: "https://medium.com/feed/dream11-tech-blog",
    feedType: "rss",
    color: "#D44128",
  },
  {
    name: "Ola",
    slug: "ola",
    logo: "https://www.google.com/s2/favicons?domain=olacabs.com&sz=128",
    website: "https://olacabs.com",
    blogUrl: "https://medium.com/ola-engineering",
    feedUrl: "https://medium.com/feed/ola-engineering",
    feedType: "rss",
    color: "#35A853",
  },
  {
    name: "Paytm",
    slug: "paytm",
    logo: "https://www.google.com/s2/favicons?domain=paytm.com&sz=128",
    website: "https://paytm.com",
    blogUrl: "https://medium.com/paytm-engineering",
    feedUrl: "https://medium.com/feed/paytm-engineering",
    feedType: "rss",
    color: "#00BAF2",
  },
  {
    name: "Myntra",
    slug: "myntra",
    logo: "https://www.google.com/s2/favicons?domain=myntra.com&sz=128",
    website: "https://myntra.com",
    blogUrl: "https://medium.com/myntra-engineering",
    feedUrl: "https://medium.com/feed/myntra-engineering",
    feedType: "rss",
    color: "#FF3F6C",
  },
  {
    name: "Freshworks",
    slug: "freshworks",
    logo: "https://www.google.com/s2/favicons?domain=freshworks.com&sz=128",
    website: "https://freshworks.com",
    blogUrl: "https://medium.com/freshworks-engineering-blog",
    feedUrl: "https://medium.com/feed/freshworks-engineering-blog",
    feedType: "rss",
    color: "#F26522",
  },
  {
    name: "Nykaa",
    slug: "nykaa",
    logo: "https://www.google.com/s2/favicons?domain=nykaa.com&sz=128",
    website: "https://nykaa.com",
    blogUrl: "https://medium.com/nykaa-engineering",
    feedUrl: "https://medium.com/feed/nykaa-engineering",
    feedType: "rss",
    color: "#FC2779",
  },
  {
    name: "Lenskart",
    slug: "lenskart",
    logo: "https://www.google.com/s2/favicons?domain=lenskart.com&sz=128",
    website: "https://lenskart.com",
    blogUrl: "https://medium.com/lenskart-engineering",
    feedUrl: "https://medium.com/feed/lenskart-engineering",
    feedType: "rss",
    color: "#00BAA0",
  },
  {
    name: "Postman",
    slug: "postman",
    logo: "https://www.google.com/s2/favicons?domain=postman.com&sz=128",
    website: "https://postman.com",
    blogUrl: "https://blog.postman.com",
    feedUrl: "https://blog.postman.com/feed/",
    feedType: "rss",
    color: "#FF6C37",
  },
  {
    name: "Zoho",
    slug: "zoho",
    logo: "https://www.google.com/s2/favicons?domain=zoho.com&sz=128",
    website: "https://zoho.com",
    blogUrl: "https://www.zoho.com/blog/technology",
    feedUrl: "https://www.zoho.com/blog/rss/zoho-blog.xml",
    feedType: "rss",
    color: "#C8202B",
  },
  {
    name: "Browserstack",
    slug: "browserstack",
    logo: "https://www.google.com/s2/favicons?domain=browserstack.com&sz=128",
    website: "https://browserstack.com",
    blogUrl: "https://www.browserstack.com/blog/engineering",
    feedUrl: "https://www.browserstack.com/blog/feed/",
    feedType: "rss",
    color: "#FF6633",
  },
  {
    name: "Hasura",
    slug: "hasura",
    logo: "https://www.google.com/s2/favicons?domain=hasura.io&sz=128",
    website: "https://hasura.io",
    blogUrl: "https://hasura.io/blog",
    feedUrl: "https://hasura.io/blog/rss.xml",
    feedType: "rss",
    color: "#1EB4D4",
  },
  {
    name: "Druva",
    slug: "druva",
    logo: "https://www.google.com/s2/favicons?domain=druva.com&sz=128",
    website: "https://druva.com",
    blogUrl: "https://www.druva.com/blog",
    feedUrl: "https://www.druva.com/blog/feed/",
    feedType: "rss",
    color: "#00B4D8",
  },
  {
    name: "Chargebee",
    slug: "chargebee",
    logo: "https://www.google.com/s2/favicons?domain=chargebee.com&sz=128",
    website: "https://chargebee.com",
    blogUrl: "https://www.chargebee.com/blog",
    feedUrl: "https://www.chargebee.com/blog/feed/",
    feedType: "rss",
    color: "#FF6B35",
  },
  {
    name: "Dunzo",
    slug: "dunzo",
    logo: "https://www.google.com/s2/favicons?domain=dunzo.com&sz=128",
    website: "https://dunzo.com",
    blogUrl: "https://medium.com/dunzo",
    feedUrl: "https://medium.com/feed/dunzo",
    feedType: "rss",
    color: "#00D290",
  },
  {
    name: "Urban Company",
    slug: "urbancompany",
    logo: "https://www.google.com/s2/favicons?domain=urbancompany.com&sz=128",
    website: "https://urbancompany.com",
    blogUrl: "https://medium.com/urbancompany-engineering",
    feedUrl: "https://medium.com/feed/urbancompany-engineering",
    feedType: "rss",
    color: "#8B5CF6",
  },
  {
    name: "Hotstar",
    slug: "hotstar",
    logo: "https://www.google.com/s2/favicons?domain=hotstar.com&sz=128",
    website: "https://hotstar.com",
    blogUrl: "https://blog.hotstar.com",
    feedUrl: "https://medium.com/feed/disney-streaming",
    feedType: "rss",
    color: "#1F2937",
  },
  {
    name: "Cure.fit",
    slug: "curefit",
    logo: "https://www.google.com/s2/favicons?domain=cult.fit&sz=128",
    website: "https://cult.fit",
    blogUrl: "https://medium.com/curefit-engineering",
    feedUrl: "https://medium.com/feed/curefit-engineering",
    feedType: "rss",
    color: "#FF0055",
  },
];
